<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQvac33w\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQvac33w/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerQvac33w.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerQvac33w\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerQvac33w\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Qvac33w',
    'container.build_id' => '91e048e2',
    'container.build_time' => 1529769411,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerQvac33w');
